
######################
# CDS Hooks Settings 
#######################
[hooks]
  URL = "http://XXX_CDS_PUBLIC_IP_ADDRESS_XXX:8083"

  # Disable all hooks executions
  disable = false

  # Number of execution to keep
  executionHistory = 10

  # Name of this CDS Hooks Service
  # Enter a name to enable this service
  name = "cds-hooks"

  # Execution retry delay in seconds
  retryDelay = 120

  # Retry execution while this number of error is not reached
  retryError = 3

  # Public url for external call (webhook)
  urlPublic = "http://XXX_CDS_PUBLIC_IP_ADDRESS_XXX:8083"

  ######################
  # CDS API Settings 
  #######################
  [hooks.api]
    maxHeartbeatFailures = 10
    requestTimeout = 10
    token = token = "XXX_GITHUB_SHARED_INFRA_TOKEN_XXX" 

    [hooks.api.grpc]
      # insecure = false
      #url = "http://localhost:8082"

    [hooks.api.http]
      # insecure = false
      url = "http://localhost:8081"

  ######################
  # CDS Hooks Cache Settings 
  #######################
  [hooks.cache]
    ttl = 60

    # Connect CDS to a redis cache If you more than one CDS instance and to avoid losing data at startup
    [hooks.cache.redis]

      # If your want to use a redis-sentinel based cluster, follow this syntax! <clustername>@sentinel1:26379,sentinel2:26379,sentinel3:26379
      host = "localhost:6379"
      password = ""

  ######################
  # CDS Hooks HTTP Configuration 
  #######################
  [hooks.http]

    # Listen address without port, example: 127.0.0.1
    # addr = ""
    port = 8083

#####################
# CDS Logs Settings 
#####################
[log]

  # Log Level: debug, info, warning, notice, critical
  level = ""

  [log.graylog]

    # Example: X-OVH-TOKEN. You can use many keys: aaa,bbb
    extraKey = ""

    # value for extraKey field. For many keys: valueaaa,valuebbb
    extraValue = ""

    # Example: thot.ovh.com
    host = ""

    # Example: 12202
    port = 0

    # tcp or udp
    protocol = ""

