- hosts: 127.0.0.1   
  become: true
  become_user: root
  connection: local
  gather_facts: no

  tasks:
    - name: Make sure inventory hosts are updated in /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: present
        regexp: ".*{{ hostvars[item]['inventory_hostname'] }}$"
        line: "{{ hostvars[item]['ansible_ssh_host'] }} {{ hostvars[item]['inventory_hostname'] }}"
      with_items:
        - "{{ groups['all'] }}"
