---
# file: ansible/nginx.yml
- hosts: cds-postgresql
  remote_user: ubuntu
  become: true
  become_user: root
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  roles:
    - common
    - postgresql
